/* PRODUCTION STORY ENGINE — one coordinated GSAP system */
'use strict';
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
function init(){
 if(typeof gsap==='undefined'||typeof ScrollTrigger==='undefined')return;
 gsap.registerPlugin(ScrollTrigger);
 const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches, coarse=matchMedia('(pointer:coarse)').matches;
 const scrollTo=el=>{if(window.__lenis)window.__lenis.scrollTo(el,{offset:-72,duration:1.1});else el.scrollIntoView({behavior:'smooth',block:'start'})};
 /* theme */ const html=document.documentElement,themeBtn=$('#themeToggle'); const saved=localStorage.getItem('yoge-theme')||'dark';html.dataset.theme=saved;themeBtn?.addEventListener('click',()=>{html.dataset.theme=html.dataset.theme==='dark'?'light':'dark';localStorage.setItem('yoge-theme',html.dataset.theme);ScrollTrigger.refresh()});
 /* nav */ const nav=$('#mainNav'),menu=$('#mobileMenu'),toggle=$('#menuToggle'),close=$('#mobileClose');let raf=0;addEventListener('scroll',()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;nav?.classList.toggle('is-scrolled',scrollY>40);const max=document.documentElement.scrollHeight-innerHeight;const fill=$('.scroll-progress__fill');if(fill)fill.style.width=(max?scrollY/max*100:0)+'%';})},{passive:true});
 const open=()=>{menu?.classList.add('is-open');toggle?.classList.add('is-open');document.body.style.overflow='hidden'},shut=()=>{menu?.classList.remove('is-open');toggle?.classList.remove('is-open');document.body.style.overflow=''};toggle?.addEventListener('click',open);close?.addEventListener('click',shut);$('.mobile-menu__backdrop')?.addEventListener('click',shut);
 $$('.nav-link[href^="#"],.mobile-link[href^="#"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const el=$(a.getAttribute('href'));if(el){shut();scrollTo(el)}}));$('.nav-logo')?.addEventListener('click',e=>{e.preventDefault();window.__lenis?window.__lenis.scrollTo(0):scrollTo(document.body)});$('#topButton')?.addEventListener('click',()=>window.__lenis?window.__lenis.scrollTo(0):scrollTo(document.body));
 /* loading */ const loader=$('#loadingScreen');const dismiss=()=>{if(!loader||loader.dataset.done)return;if(loader)loader.dataset.done='1',loader.classList.add('is-done');setTimeout(()=>loader?.classList.add('is-hidden'),850)};addEventListener('load',()=>setTimeout(dismiss,700));setTimeout(dismiss,2800);
 if(!reduce&&!coarse){const dot=$('.cursor__dot'),ring=$('.cursor__ring');let x=-100,y=-100,rx=x,ry=y;document.addEventListener('pointermove',e=>{x=e.clientX;y=e.clientY;dot&&(dot.style.transform=`translate(${x}px,${y}px) translate(-50%,-50%)`);dot&&(dot.style.opacity=1)},{passive:true});(function cursor(){rx+=(x-rx)*.14;ry+=(y-ry)*.14;ring&&(ring.style.transform=`translate(${rx}px,${ry}px) translate(-50%,-50%)`);requestAnimationFrame(cursor)})();
 }
 /* hero entry */ if(!reduce){gsap.timeline({delay:.15}).fromTo('.hero-image__mask',{clipPath:'inset(100% 0 0 0)'},{clipPath:'inset(0 0 0 0)',duration:1.15,ease:'power4.inOut'}).fromTo('.hero-kicker,.hero-headline',{opacity:0,y:28},{opacity:1,y:0,duration:.8,stagger:.08},.2).fromTo('.hero-tagline,.hero-metrics,.hero-cta',{opacity:0,y:18},{opacity:1,y:0,duration:.7,stagger:.1},.55).fromTo('.hero-badge',{opacity:0,y:14},{opacity:1,y:0,duration:.7},.7);}
 /* chapter reveal */ $$('.story-section:not(.hero-section)').forEach(section=>{const head=$('.section-header',section);if(head&&!reduce)gsap.from(head,{y:50,opacity:0,duration:.9,ease:'power3.out',scrollTrigger:{trigger:section,start:'top 78%',once:true}});$$('.origin-card,.timeline-entry__card,.project-card,.battle-card,.result-card,.cert-item,.contact-card',section).forEach((el,i)=>{if(reduce)return;gsap.from(el,{y:60,opacity:0,rotateX:i%2?3:-3,transformPerspective:1000,duration:.8,delay:(i%4)*.08,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}})});});
 /* hero scroll narrative */ if(!reduce&&!matchMedia('(max-width:1023px)').matches)gsap.timeline({scrollTrigger:{trigger:'.hero-section',start:'top top',end:'+=85%',scrub:.7,pin:true}}).to('.hero-image-wrapper',{scale:1.12,yPercent:-7},0).to('.hero-right',{yPercent:-16,opacity:.05},.18).to('.hero-exit-overlay',{opacity:1},.68);
 /* project depth */ if(!reduce){gsap.utils.toArray('.project-hero__visual,.section-bg__orb,.battle-featured__glow').forEach(el=>gsap.to(el,{yPercent:-12,ease:'none',scrollTrigger:{trigger:el.closest('.story-section'),start:'top bottom',end:'bottom top',scrub:1.4}}));gsap.utils.toArray('.timeline__progress').forEach(el=>gsap.to(el,{height:'100%',ease:'none',scrollTrigger:{trigger:'.timeline',start:'top 70%',end:'bottom 30%',scrub:1}}));}
 /* skills */ $$('.skill-bar__fill').forEach(bar=>{const w=bar.dataset.width||'80';bar.style.width='0%';if(reduce){bar.style.width=w+'%';return}gsap.to(bar,{width:w+'%',duration:1.3,ease:'power3.out',scrollTrigger:{trigger:bar,start:'top 90%',once:true}})});
 /* research counters */ $$('.result-card__number').forEach(el=>{const end=Number(el.dataset.count||el.textContent)||0;if(reduce)return;const o={v:0};gsap.to(o,{v:end,duration:1.6,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 90%',once:true},onUpdate:()=>el.textContent=Math.round(o.v)})});
 /* spotlight */ if(!coarse){const hero=$('.hero-section');hero?.addEventListener('pointermove',e=>{const r=hero.getBoundingClientRect();hero.style.setProperty('--sx',((e.clientX-r.left)/r.width*100)+'%');hero.style.setProperty('--sy',((e.clientY-r.top)/r.height*100)+'%')},{passive:true})}
 /* subtle card tilt */ if(!coarse&&!reduce&&typeof VanillaTilt!=='undefined')VanillaTilt.init($$('.origin-card,.project-card,.battle-card'),{max:5,speed:650,scale:1.015,glare:false,gyroscope:false,perspective:1100});
 /* dynamic chapter markers */ $$('.story-section[id]').forEach(sec=>{ScrollTrigger.create({trigger:sec,start:'top 45%',end:'bottom 45%',onEnter:()=>sec.classList.add('is-active'),onEnterBack:()=>sec.classList.add('is-active'),onLeave:()=>sec.classList.remove('is-active'),onLeaveBack:()=>sec.classList.remove('is-active')})});
 ScrollTrigger.refresh();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
